language: java
jdk:
- openjdk6
before_install:
- python travis.py --mirrors;
install:
- mvn install -DskipTests=true
env:
  global:
  - SONATYPE_USERNAME=deployment
  - secure: cN7sISzeL6QiWJvyBaQn6ML4jhLRcvcdr5xIRKYc/gN/jtI59jhBNHMGe/lJmFYhZTqxmIrQo1xKTwNPnaKG3l1t99gMZ/9/HUICZ0a2cr+giHo4x+d8/DsrzNgRYZNUb4pRgXmqxfmEflp/NDcwj++ZuM0GXJePploBDIkm1tw=
after_success:
- '[[ $TRAVIS_REPO_SLUG == telefonicaid* ]] && [[ $TRAVIS_PULL_REQUEST == "false"
  ]] && [[ $TRAVIS_BRANCH == "master" ]] && { python travis.py --deploy; mvn deploy
  -DskipTests=true; };'
- '[[ $TRAVIS_REPO_SLUG == telefonicaid* ]] && [[ $TRAVIS_PULL_REQUEST == "false"
  ]] && [[ $TRAVIS_BRANCH == "develop" ]] && { python travis.py --deploy; mvn deploy
  -DskipTests=true; };'
